name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container: ubuntu:20.04
    steps:
      - name: Obtain Latest Git ONLY within container for checkout
        run: |
          apt-get update
          apt-get install -y git

      - name: Checkout
        uses: actions/checkout@master

      - name: vuepress-deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
         ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
         TARGET_REPO: kamaljitdevnagri/devnagri_docs.github.io
         TARGET_BRANCH: docs
         BUILD_SCRIPT: yarn && yarn docs:build
         BUILD_DIR: public/
         CNAME: https://docs2.devnagri.dev
